### ISSUE TITLE
请问如何在plugin中得到发信息者的QQ号码？

### ISSUE THREAD

**Issue by bypassfuture** [JixunMoe/jjBot#14]
你好，
jjBOT很好用。这两天我在试着编写 jjBOT 的plugin。请问，如何在plugin中得到QQ群中发信息者的QQ号码？
msg.user 数组只有 { nick: '',
    province: '',
    gender: 'unknown',
    uin:,
    country: '',
    city: '',
    profileName: '' },
而没有记录号码这一项。

谢谢！

**Comment by JixunMoe** [comment]
当前版本([指这个 commit](https://github.com/JixunMoe/jjBot/commit/ec61a380d070fa03aba58b00540c877a330a9ad7))会写入 `msg.ucdata`，内包含抓取到的号码。

```js
{
	qNum: 'QQ 号',
	isNew: true, // 是否为新用户
	pems: {can: [], no: []} // 相关权限
}
```

**Comment by JixunMoe** [comment]
没有回复的话我明天就关 issue 了哦~

**Comment by bypassfuture** [comment]
哦，不好意思 ,没有注意你的回复 0_o
我测试了， msg.ucdata.qNum 确实可以获取发信息者的QQ号码。
现在没问题了。

谢谢！

**Comment by JixunMoe** [comment]
没问题ww 这个新的东西也是最近才加上来的。
