### ISSUE TITLE
关于机器人被T的问题

### ISSUE THREAD

**Issue by bypassfuture** [JixunMoe/jjBot#16]
你好，
在使用机器人时，有时只发了一条信息，就被T下线。在shell中显示：

**[4:8:18][ERR ]: 机器人被T下线; 如果您是开发者请启用 --offline 进入离线模式调试避免占线。**

tx的检测算法是如何检测出来的呢，他怎么得知这个账号是在使用机器人？有什么好的方法可以避免被T么？

谢谢！

---------------
edit : 每次被T下线后就被封号。用高等级的号能解决问题么？还是要注册会员 ? : /

**Comment by NijiharaTsubasa** [comment]
因为机器人的回复太模式化了，被腾讯学习了
解决方法只有让回复更加多样化，我自从写了一个聊天插件后就没被封了，但那个插件还远不到能公开提供的程度

**Comment by NijiharaTsubasa** [comment]
封号无解，只能发短信去解，注意一个手机号最多解三次，然后必须换手机号
有人说等级高于1颗星的被封的几率小一些

**Comment by bypassfuture** [comment]
ok,明白了，清楚思路就好说了。
